[package]
name = "demoscene"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
anyhow = "1"
fxhash = "0.2"
gstreamer = "0.18"
lofty = "0.6"
md5 = "0.7"
netidx-container = { version = "0.10", path = "../netidx/netidx-container" }
netidx-tools = { version = "0.10", path = "../netidx/netidx-tools" }
netidx = { version = "0.10", path = "../netidx/netidx" }
sled = { version = "0.34", features = ["zstd", "compression"] }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
rayon = "1"
